# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Recieve.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Recieve_Message(object):
    def setupUi(self, Recieve_Message):
        Recieve_Message.setObjectName("Recieve_Message")
        Recieve_Message.resize(400, 300)
        self.layoutWidget = QtWidgets.QWidget(Recieve_Message)
        self.layoutWidget.setGeometry(QtCore.QRect(7, 22, 381, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Recieve_Message)
        QtCore.QMetaObject.connectSlotsByName(Recieve_Message)

    def retranslateUi(self, Recieve_Message):
        _translate = QtCore.QCoreApplication.translate
        Recieve_Message.setWindowTitle(_translate("Recieve_Message", "Recieve Message"))
        self.label.setText(_translate("Recieve_Message", "Message:"))
