# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Create.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_Create(object):
    def setupUi(self, Window_Create):
        Window_Create.setObjectName("Window_Create")
        Window_Create.resize(400, 300)
        self.New_Username_Label = QtWidgets.QLabel(Window_Create)
        self.New_Username_Label.setGeometry(QtCore.QRect(94, 90, 51, 16))
        self.New_Username_Label.setObjectName("New_Username_Label")
        self.New_Password_field = QtWidgets.QLineEdit(Window_Create)
        self.New_Password_field.setGeometry(QtCore.QRect(150, 116, 133, 20))
        self.New_Password_field.setObjectName("New_Password_field")
        self.New_Password_label = QtWidgets.QLabel(Window_Create)
        self.New_Password_label.setGeometry(QtCore.QRect(93, 116, 50, 16))
        self.New_Password_label.setObjectName("New_Password_label")
        self.New_Username_Field = QtWidgets.QLineEdit(Window_Create)
        self.New_Username_Field.setGeometry(QtCore.QRect(151, 90, 133, 20))
        self.New_Username_Field.setObjectName("New_Username_Field")
        self.Create_Accoun_Button = QtWidgets.QPushButton(Window_Create)
        self.Create_Accoun_Button.setGeometry(QtCore.QRect(151, 171, 83, 23))
        self.Create_Accoun_Button.setObjectName("Create_Accoun_Button")
        # Buttons go here

        

        self.retranslateUi(Window_Create)
        QtCore.QMetaObject.connectSlotsByName(Window_Create)

    def retranslateUi(self, Window_Create):
        _translate = QtCore.QCoreApplication.translate
        Window_Create.setWindowTitle(_translate("Window_Create", "Create Account"))
        self.New_Username_Label.setText(_translate("Window_Create", "username:"))
        self.New_Password_label.setText(_translate("Window_Create", "password:"))
        self.Create_Accoun_Button.setText(_translate("Window_Create", "Create Account"))
