# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_Login(object):
    def setupUi(self, Window_Login):
        Window_Login.setObjectName("Window_Login")
        Window_Login.resize(400, 300)
        Window_Login.setAccessibleName("")
        self.Password_label = QtWidgets.QLabel(Window_Login)
        self.Password_label.setGeometry(QtCore.QRect(94, 116, 50, 16))
        self.Password_label.setObjectName("Password_label")
        self.Username_Label = QtWidgets.QLabel(Window_Login)
        self.Username_Label.setGeometry(QtCore.QRect(94, 90, 51, 16))
        self.Username_Label.setObjectName("Username_Label")
        self.Login_Button = QtWidgets.QPushButton(Window_Login)
        self.Login_Button.setGeometry(QtCore.QRect(151, 142, 75, 23))
        self.Login_Button.setObjectName("Login_Button")
        self.Create_Prompt_Button = QtWidgets.QPushButton(Window_Login)
        self.Create_Prompt_Button.setGeometry(QtCore.QRect(151, 171, 83, 23))
        self.Create_Prompt_Button.setObjectName("Create_Prompt_Button")
        self.Username_Field = QtWidgets.QLineEdit(Window_Login)
        self.Username_Field.setGeometry(QtCore.QRect(151, 90, 133, 20))
        self.Username_Field.setObjectName("Username_Field")
        self.Password_field = QtWidgets.QLineEdit(Window_Login)
        self.Password_field.setGeometry(QtCore.QRect(151, 116, 133, 20))
        self.Password_field.setObjectName("Password_field")
        # Buttons go here



        self.retranslateUi(Window_Login)
        QtCore.QMetaObject.connectSlotsByName(Window_Login)

    def retranslateUi(self, Window_Login):
        _translate = QtCore.QCoreApplication.translate
        Window_Login.setWindowTitle(_translate("Window_Login", "Login"))
        self.Password_label.setText(_translate("Window_Login", "password:"))
        self.Username_Label.setText(_translate("Window_Login", "username:"))
        self.Login_Button.setText(_translate("Window_Login", "Login"))
        self.Create_Prompt_Button.setText(_translate("Window_Login", "Create Account"))
