# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_Main(object):
    def setupUi(self, Window_Main):
        Window_Main.setObjectName("Window_Main")
        Window_Main.resize(400, 300)
        self.New_Keys_Button = QtWidgets.QPushButton(Window_Main)
        self.New_Keys_Button.setGeometry(QtCore.QRect(-1, -1, 75, 23))
        self.New_Keys_Button.setObjectName("New_Keys_Button")
        self.widget = QtWidgets.QWidget(Window_Main)
        self.widget.setGeometry(QtCore.QRect(32, 41, 310, 249))
        self.widget.setObjectName("widget")
        self.Window_Main_Layout = QtWidgets.QGridLayout(self.widget)
        self.Window_Main_Layout.setContentsMargins(0, 0, 0, 0)
        self.Window_Main_Layout.setObjectName("Window_Main_Layout")
        self.Recipient_Username_Label = QtWidgets.QLabel(self.widget)
        self.Recipient_Username_Label.setObjectName("Recipient_Username_Label")
        self.Window_Main_Layout.addWidget(self.Recipient_Username_Label, 0, 1, 1, 1)
        self.Recipient_Username_Field = QtWidgets.QLineEdit(self.widget)
        self.Recipient_Username_Field.setObjectName("Recipient_Username_Field")
        self.Window_Main_Layout.addWidget(self.Recipient_Username_Field, 0, 2, 1, 1)
        self.Message_Label = QtWidgets.QLabel(self.widget)
        self.Message_Label.setObjectName("Message_Label")
        self.Window_Main_Layout.addWidget(self.Message_Label, 1, 0, 1, 1)
        self.Message_Field = QtWidgets.QPlainTextEdit(self.widget)
        self.Message_Field.setObjectName("Message_Field")
        self.Window_Main_Layout.addWidget(self.Message_Field, 1, 1, 1, 2)
        self.Send_Button = QtWidgets.QPushButton(self.widget)
        self.Send_Button.setObjectName("Send_Button")
        self.Window_Main_Layout.addWidget(self.Send_Button, 2, 2, 1, 1)
        # Buttons go here



        self.retranslateUi(Window_Main)
        QtCore.QMetaObject.connectSlotsByName(Window_Main)

    def retranslateUi(self, Window_Main):
        _translate = QtCore.QCoreApplication.translate
        Window_Main.setWindowTitle(_translate("Window_Main", "Send Message"))
        self.New_Keys_Button.setText(_translate("Window_Main", "refresh keys"))
        self.Recipient_Username_Label.setText(_translate("Window_Main", "user:"))
        self.Message_Label.setText(_translate("Window_Main", "message:"))
        self.Send_Button.setText(_translate("Window_Main", "Send"))
